name: Coverage > 80%

on:
  push:
  pull_request:


jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Obtaining the code
        uses: actions/checkout@v1

      - name: Build dev
        run: make dev

      - name: Check coverage
        env:
          MIN_COV: 80
        run: |
          cov=$(make coverage | grep ^TOTAL | sed -E 's/.* ([0-9]+)%$/\1/')
          echo "Overall coverage: $cov%"
          if (( $cov < $MIN_COV )); then
              echo "FAIL - Minimum coverage $MIN_COV% not reached"
              exit 1
          fi
