name: Build & Deploy [RELEASE]

on:
  release:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Obtaining the code
        uses: actions/checkout@v1

      - name: Build
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python setup.py sdist bdist_wheel

      - name: Deploy PyPi
        env:
          PYPI_PASS: ${{ secrets.RELEASE_PYPI_TOKEN }}
        run: |
          twine upload -u __token__ -p ${PYPI_PASS} dist/*
