name: Build & Deploy [RELEASE]

on:
  release:
    types: [ published ]

jobs:
  build-n-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Obtaining the code
        uses: actions/checkout@v1

      - name: Build
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install wheel
          python setup.py sdist bdist_wheel

      - name: Deploy PyPi
        env:
          PYPI_PASS: ${{ secrets.RELEASE_PYPI_TOKEN }}
        run: |
          source venv/bin/activate
          pip install twine
          twine upload -u __token__ -p ${PYPI_PASS} dist/*
